runtime: python39

entrypoint: gunicorn -b :$PORT -t 120 main:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
  max_concurrent_requests: 50

env_variables:
  GOOGLE_CLOUD_PROJECT: "jeremies-notes"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto