runtime: python39

entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

instance_class: F1

env_variables:
  GOOGLE_CLOUD_PROJECT: "jeremies-notes"