runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


- url: /static/stylesheets
  static_dir: static/stylesheets

- url: /static/images
  static_dir: static/images

- url: .*
  script: main.app



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest